Fix test cases styles
CodeChain-io/codechain-sdk-python pull request #12
Opened 2019-07-19 15:53 UTC by foriequal0

2019-07-23 06:47 UTC, posgnu requested changes

2019-07-23 06:47 UTC, GNUp commented on tests/test_Uxxx.py
> -from rlp import decode
This is a result of `reorder_python_imports` which is used by flask project. I brought most of the formatting rules from this project. https://github.com/asottile/reorder_python_imports https://github.com/pallets/flask/blob/master/.pre-commit-config.yaml

2019-07-23 06:47 UTC, GNUp commented
LGTM

2019-07-23 16:51 UTC, foriequal0 commented
I've rebased it to `master` and added/fixed some commits.

* Use more flexible language_version: python3
* Fix `import` according to PEP8 style guide
* Fix EOL
* Fill default value for __build__ in __version__.py

2019-07-24 08:12 UTC, posgnu approved these changes

2019-07-24 08:13 UTC, merged