Add to_string and to_json tests
CodeChain-io/codechain-sdk-python pull request #26
Opened 2019-10-09 18:22 UTC by GNUp

2019-10-10 09:04 UTC, foriequal0 requested changes
Can you change the name of the PR and the commit? The test is for `to_string`, not `to_json` and adding a test with the implementation is basic. I don't think we have to mention it in this case.

2019-10-13 17:28 UTC, GNUp commented
@foriequal0 Done.

2019-10-14 02:48 UTC, foriequal0 approved these changes

2019-10-18 02:20 UTC, foriequal0 approved these changes

2019-10-18 02:20 UTC, merged