Add jsondatabase dependency
CodeChain-io/codechain-sdk-python pull request #39
Opened 2019-11-09 18:48 UTC by GNUp

I set `setup.py` to use `LF`.

2019-11-10 16:21 UTC, foriequal0 requested changes
I've converted CRLF to LF all at once. Please review and merge the PR (https://github.com/CodeChain-io/codechain-sdk-python/pull/41) first and rebase this on to it.
Also I've made another PR to use more `--diff` on pre-commit hooks for CI.
https://github.com/CodeChain-io/codechain-sdk-python/pull/40 It'll help you to diagnose problems in GitHub Actions.

2019-11-10 20:26 UTC, GNUp commented
Successfully rebased.

2019-11-11 02:28 UTC, foriequal0 approved these changes

2019-11-11 03:13 UTC, foriequal0 approved these changes

2019-11-11 03:14 UTC, merged